denoland/deno_registry2

utils/storage.ts

Fixes #30 for new uploads. For existing uploads I need to fix this in deno_website2

fix: JSX and TSX extensions

---

utils/database.ts
utils/database_test.ts

fix: filter unlisted modules from total_count

---

API.md
Makefile
api/modules/get.ts
api/modules/get_test.ts
template.yaml

This returns a specific module from the database. Needed for some new website functionality.

feat: /module/{name} API endpoint

---

template.yaml

chore: add AutoPublishAlias on lambda functions (#72)

---

.github/workflows/ci.yml
tools/smoke_test.js

This is a super basic smoke test, hopefully it can help detect issues in prod more quickly. I used vanilla js just to make it a little quicker and avoid the ts check.
Fixes #73

feat: add smoke tests (#73)

---

README.md
api/modules/get_test.ts
api/modules/list_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
utils/database.ts
utils/database_test.ts

feat: max modules per user/org

---

deps.ts

fix: update deno.land/x/sqs

---

terraform/builds.tf
terraform/main.tf
terraform/modules.tf
terraform/webhook.tf

fix: match gateway and lambda timeouts

---

api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_push_test.ts

I also want to add some tests for this case, though I'm not sure how to trigger the correct conditions for this error to pop in the current integration test suite.

fix: status code for versions that already have a build queued

---

Makefile

fix: actually do 1.4.0 update

---

api/stats.ts
api/stats_test.ts
utils/database.ts
utils/database_test.ts

add total_versions to stats endpoint

---

api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
utils/database.ts
utils/database_test.ts

This adds the ability for us to block users. Name squatters be warned... 👿

feat: add ability to block users

---

api/modules/list.ts
api/modules/list_test.ts
utils/database.ts
utils/database_test.ts

feat: add sort option to module list endpoint

---

api/modules/list_test.ts
utils/database.ts

Adds the 'random' sort order to the `/modules` endpoint. It handles
the 'limit' parameter like it does normally, but ignores the 'page'
and 'query' parameters.
Fixes: #158

feat: add the random sort order to module list

---

api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_push_test.ts
utils/database.ts

fix(webhook): ignore failed builds in the webhook

---

api/modules/list.ts
api/modules/list_test.ts
utils/database.ts
utils/database_test.ts

feat: add search options used to the module list response

---

.github/workflows/ci.yml
Dockerfile
Makefile
api/async/publish.ts
api/async/publish_test.ts
api/async/stargazers_test.ts
api/stats.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts
test_deps.ts
utils/database.ts
utils/database_test.ts

Reverts denoland/deno_registry2#183
```
2020-11-22T00:43:22.276+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
-- | --
  | 2020-11-22T00:43:22.553+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:43:22.553+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:43:22.553+01:00 | ~~~~~
  | 2020-11-22T00:43:22.553+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:43:22.556+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:43:22.556+01:00 | Check the permission of the directory.
  | 2020-11-22T00:43:22.557+01:00 | error: bad deno executable
  | 2020-11-22T00:43:22.655+01:00 | START RequestId: 6bdaa3a1-db36-42f8-8ade-c501fcd33aae Version: …
```

Revert "chore: update to Deno 1.5.2"

---

terraform/main.tf

add ECR repository for Lambda deployment package

---

.github/workflows/ci.yml

fix: ci should specify only tag, not image

---

terraform/stats.tf

fix lambda entrypoint for stats endpoint

---

terraform/webhook.tf

fix: webhook lambda deployment

---

utils/utils.ts
utils/utils_test.ts

fix: directory size when folders have the same prefix

---

terraform/api.tf

setup cloudwatch logging for api gateway in default region

---

api/async/publish.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_push_test.ts

fix: allow leading slash in subdir param

---

.github/workflows/ci.yml
Dockerfile
Makefile
api/async/cleanup.ts
api/async/cleanup_test.ts
api/async/publish.ts
api/async/publish_test.ts
api/async/stargazers.ts
api/async/stargazers_test.ts
api/builds/get.ts
api/builds/get_test.ts
api/modules/get.ts
api/modules/get_test.ts
api/modules/list.ts
api/modules/list_test.ts
api/stats.ts
api/stats_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts
docker-compose.yml
run-tests.sh
test_deps.ts
utils/database.ts
utils/database_test.ts
utils/deno.ts
utils/http.ts
utils/storage.ts

This commit updates the Deno version used by the registry to 1.17.3.﻿

chore: update to Deno 1.17

---

.github/workflows/ci.yml
Dockerfile
api/async/cleanup.ts
api/async/cleanup_test.ts
api/async/publish.ts
api/async/publish_test.ts
api/async/stargazers.ts
api/async/stargazers_test.ts
api/builds/get.ts
api/builds/get_test.ts
api/modules/get.ts
api/modules/get_test.ts
api/modules/list.ts
api/modules/list_test.ts
api/stats.ts
api/stats_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts
docker-compose.yml
run-tests.sh
test_deps.ts
utils/database.ts
utils/database_test.ts
utils/deno.ts
utils/http.ts
utils/storage.ts

Reverts denoland/deno_registry2#268

Revert "chore: update to Deno 1.17"

---

.github/workflows/ci.yml
Dockerfile
Makefile
api/async/cleanup.ts
api/async/cleanup_test.ts
api/async/publish.ts
api/async/publish_test.ts
api/async/stargazers.ts
api/async/stargazers_test.ts
api/builds/get.ts
api/builds/get_test.ts
api/modules/get.ts
api/modules/get_test.ts
api/modules/list.ts
api/modules/list_test.ts
api/stats.ts
api/stats_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts
docker-compose.yml
run-tests.sh
test_deps.ts
utils/database.ts
utils/database_test.ts
utils/deno.ts
utils/http.ts
utils/storage.ts

Reland of #268
Fixes an issue in the Docker image (this is the only thing not tested locally).

[RELAND] chore: update to Deno 1.17

---

.github/workflows/ci.yml
Dockerfile
api/async/cleanup.ts
api/async/cleanup_test.ts
api/async/publish.ts
api/async/publish_test.ts
api/async/stargazers.ts
api/async/stargazers_test.ts
api/builds/get.ts
api/builds/get_test.ts
api/modules/get.ts
api/modules/get_test.ts
api/modules/list.ts
api/modules/list_test.ts
api/stats.ts
api/stats_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts
docker-compose.yml
run-tests.sh
test_deps.ts
utils/database.ts
utils/database_test.ts
utils/deno.ts
utils/http.ts
utils/storage.ts

Reverts denoland/deno_registry2#274
This is just in case I break prod again.

Revert "[RELAND] chore: update to Deno 1.17"

---

.github/workflows/ci.yml
Dockerfile
Makefile
api/async/cleanup.ts
api/async/cleanup_test.ts
api/async/publish.ts
api/async/publish_test.ts
api/async/stargazers.ts
api/async/stargazers_test.ts
api/builds/get.ts
api/builds/get_test.ts
api/modules/get.ts
api/modules/get_test.ts
api/modules/list.ts
api/modules/list_test.ts
api/stats.ts
api/stats_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts
docker-compose.yml
run-tests.sh
test_deps.ts
utils/database.ts
utils/database_test.ts
utils/deno.ts
utils/http.ts
utils/storage.ts

Second reland of #274
Fixes another issue, this time related to the format of the mongodb_uri. :fingers_crossed: this is the last one.

[RELAND 2] chore: update to Deno 1.17

---

.github/workflows/ci.yml
Dockerfile
api/async/cleanup.ts
api/async/cleanup_test.ts
api/async/publish.ts
api/async/publish_test.ts
api/async/stargazers.ts
api/async/stargazers_test.ts
api/builds/get.ts
api/builds/get_test.ts
api/modules/get.ts
api/modules/get_test.ts
api/modules/list.ts
api/modules/list_test.ts
api/stats.ts
api/stats_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts
docker-compose.yml
run-tests.sh
test_deps.ts
utils/database.ts
utils/database_test.ts
utils/deno.ts
utils/http.ts
utils/storage.ts

Reverts denoland/deno_registry2#276
In case I break it again.

Revert "[RELAND 2] chore: update to Deno 1.17"

---

.github/workflows/ci.yml

Reverts denoland/deno_registry2#312

Revert "fix(terraform): set GCP credentials correctly, and quote vars with spaces"

---

.github/workflows/ci.yml
api/async/cleanup.ts
api/async/cleanup_test.ts
api/async/publish_test.ts
api/async/stargazers.ts
api/async/stargazers_test.ts
api/builds/get_test.ts
api/modules/get.ts
api/modules/get_test.ts
api/modules/list.ts
api/modules/list_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
terraform/alerts.tf
terraform/cleanup.tf
terraform/modules.tf
utils/database.ts
utils/database_test.ts
utils/datastore_database.ts
utils/test_utils.ts
utils/types.ts

Reverts denoland/deno_registry2#324

Revert "refactor: use datastore for modules"

---

utils/datastore_database.ts

refactor: new structure for builds

---

api/async/publish.ts
api/async/publish_test.ts
api/builds/get_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_push_test.ts
utils/database_test.ts
utils/datastore_database.ts
utils/test_utils.ts
utils/types.ts

refactor: remove legacy_builds
