denoland/deno_registry2

template.yaml

Add a second queue to the SAM template and adds a parameter for the visibility
timeout. This allows setting a lower value than the 5 minutes used in production,
which makes it easier to test locally.
For the maxReceiveCount setting, 5 was chosen as it makes for a sensible default
value.
Closes #60
---
I left the queue parameters with their default values, so _if_ messages do get in the DQL, they'll stay there for at most 4 days. I'm also not adding anything to process the messages from the DQL, as mentioned in the issue there isn't an issue with failing builds right now so its not a top priority. At the very least I think we could add a cloudwatch alarm when there are messages older than say a day in the DQL, but I didn't want to go too far with this PR.
I really wanted to find a way to …

feat: Add Dead Letter Queue for SQS

---

api/async/publish.ts
api/async/publish_test.ts
api/webhook/github_push_test.ts
run-tests.sh
template.yaml
utils/database.ts
utils/deno.ts
utils/storage.ts

Towards #35 
This PR adds a `meta/deps.json` file for each new version. Each file js and ts file in the repository is individually analyzed and then stitched into a single dependency graph.
<details>
<summary>meta/deps.json example</summary>
```json
{
"graph":{
"nodes":{
"http://s3:9000/deno-registry2/ltest/versions/0.0.9/raw/deps.ts":{
"imports":[
"https://deno.land/std@0.64.0/uuid/mod.ts"
]
},
"https://deno.land/std@0.64.0/uuid/mod.ts":{
"imports":[
"https://deno.land/std@0.64.0/uuid/v1.ts",
"https://deno.land/std@0.64.0/uuid/v4.ts",
"https://deno.land/std@0.64.0/uuid/v5.ts"
]
},
"https://deno.land/std@0.64.0/uuid/v1.ts":{
"imports":[
"https://deno.land/std@0.64.0/uuid/_common.ts"
]
},
"https://deno.land/std@0.64.0/uuid/_common.ts":{
"imports":[
]
}, …
```

feat: dependency analysis

---

utils/database.ts

#59 introduced a bug where searching modules does not work at all. This fixes that.

fix: search not working

---

.github/workflows/ci.yml
worker/worker.js

Due to the new terraform deployment on the registry we have a new s3 bucket - it is fully in sync with the current one.

Actually use terraform deployment

---

terraform/publish.tf

I messed this up during the terraform switch - publishes are not actually going through at the minute.

fix: trigger async_publish lambda on build queue

---

api/modules/list.ts
utils/database.ts

Adds visibility in the Lambda logs when connection to mongodb fails, Fixes #74 
Note, this is a big ol' patch of duct tape to give a little more visibility that there's an issue with the database connection. Ultimately, the issue comes from the underlying mongodb library that just assigns undefined to the clientId instead of raising an error. A long term fix would require either submitting a change to the mongo lib, or use a different one

fix: silent error when database connection fails (#74)

---

.github/workflows/ci.yml
terraform/alerts.tf
terraform/meta.tf
terraform/providers.tf
terraform/publish.tf
terraform/terraform.tfvars.example
terraform/variables.tf

* add an alarm for total execution errors over 10 minutes for each
lambda function
* add an alarm for old messages in the build queue
* add an alarm for total visible messages in the dead letter queue
* parameterized the aws region
Make sure to create at least one topic subscription after rolling out these changes to get notified by alerts.
Fixes #75

chore: add cloudwatch alarms

---

.gitignore
terraform/alerts.tf
terraform/iam.tf

New module uploads are failing because of this right now. Also increased sensitivity on cloudwatch alerts to catch this error.
This is needed because s3::GetObject returns 403 on not found if ListBuckets permission is not present.

fix: add listbucket iam permission

---

terraform/builds.tf
terraform/modules.tf
terraform/publish.tf
terraform/webhook.tf

This was one of the reasons to switch to Terraform: easily enable Lambda
versioning using the `publish` option.

ops: add publish option to lambda functions

---

.github/workflows/ci.yml
terraform/iam.tf
terraform/main.tf
terraform/providers.tf
terraform/terraform.tfvars.example
terraform/variables.tf

Add a replication configuration to keep a backup of modules in a different (parameterized) AWS region. A lifecycle policy has been set on the backup bucket so that objects transition to standard infrequent access over time to save on storage costs.
Fixes #90

ops: add replication configuration

---

utils/deno.ts

Fixes #119.
I tested this locally. Is there an upstream Deno bug for this behaviour? I don't think it should just hang if you do `output` before `status`...

fix: get deno info output before getting status

---

api/async/publish.ts
test_deps.ts
utils/testdata/deno-v1.3.2.json
utils/utils.ts
utils/utils_test.ts

according to the benchmarks I did locally:
```
before: 34582.116427ms
after:   1899.9781679999999ms
```
I used the deno directory @ v1.3.2 to run my tests to have a pretty real-world use-case.

feat: optimize directory size calculations

---

api/worker.js

This sets a strict `Content-Security-Policy` for all resources returned from `cdn.deno.land`.

fix: set content security policy

---

api/stats.ts
api/stats_test.ts

Felt like this might be a useful info for the `/stats/` endpoint. I used the `total_count` because that's what's used in the modules list endpoint, but it clashes with the other keys of this endpoint so I'm not sure about that.

feat: add total number of modules to stat endpoint

---

api/async/publish.ts
api/async/publish_test.ts
api/stats_test.ts
utils/deno.ts
utils/storage.ts

I had to create a new file revision for this, because the old `deps.json` has very very long cache headers.

refactor: add deps_v2.json that includes size

---

api/modules/list.ts
api/modules/list_test.ts
utils/database.ts

This will be used for the generic version of import IntelliSense in the VS Code extension.

feat: add short param for GET /modules

---

Makefile
README.md

I got tired of running test via the long docker-compose command. Now it's as easy as `make test`.

chore: add tests to makefile

---

api/async/publish_test.ts
api/async/stargazers_test.ts
api/builds/get_test.ts
api/modules/get_test.ts
api/modules/list_test.ts
api/stats_test.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
utils/test_utils.ts

moves all test functions into a try/finally statement where the finally block contains the cleanup steps.
tested by sprinkling assertion errors here and there and making sure they didn't cascade like they used to.
Fixes #144

chore: avoid cascading failures in tests

---

api/async/publish_test.ts
api/async/stargazers_test.ts
api/builds/get_test.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts

Upgrade the s3 dependency to v0.2.0 to benefit from the addition
of the `empty` method. This way we can more easily cleanup after
tests without having to know exactly how many objects are created
in the s3 bucket and what their keys are.

chore: improve test cleanup

---

api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_push_test.ts

First pass at cleaning up the webhook function handler. I haven't changed the general flow of the code, mostly worked in the `checkAvailable` and `initiateBuild` functions since I felt they were the hardest to navigate.
---
Adds new interface for webhook handler functions. Also adds jsdoc
comments for each event, based on [this
docs](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/github-event-types).
bring checkBlocked return value into its own function
move check for repo id into its own function
move the check for number of modules per repo into its own function.
move the owner quota check into its own function
move module name validation into its own function
first pass at simplifying codeflow of check available function
remove check for `!entry` as it …

chore: refactor webhook function

---

api/async/publish.ts
api/async/publish_test.ts
utils/database.ts

Instead of checking that each individual file is under 2.5 mb, we now check that the total of all files is under 20mb. This gives users more flexibility to have big files (for WASM).
cc @eliassjogreen

feat: add total module size limit

---

api/async/stargazers.ts
api/builds/get.ts
api/modules/get.ts
api/modules/list.ts
api/stats.ts
api/webhook/github.ts
utils/types.ts

Fixes #173 may not be worth registering a module just for the types, but at least now they will be available on doc.deno.land
Here's what it looks like on [doc.deno.land](https://doc.deno.land/https/raw.githubusercontent.com/wperron/deno_registry2/feat/api-types/utils/types.ts)

add type definitions for the different API reponse body

---

terraform/iam.tf

First commit to address #197 -- I want to enable Active tracing manually before I port it to the tf config, having the IAM policy already in place just makes it easier

add x-ray write IAM policy

---

api/async/publish.ts
utils/git.ts

fixes #217
Previously, large git repositories could cause the Lambda /tmp to run out of space.  This PR introduces  a git clone filter which avoids fetching all blobs, and then does a sparse checkout of only the subdir (if specified).

feat: use git clone filter and sparse checkout

---

api/async/publish.ts
utils/git.ts

Looks like the version of Git installed on the Docker image is too old to have the `sparse` option. I'm reverting quickly and will look into fixing the issue for good tomorrow.
This reverts commit ce7c35b3e10e69856f906c7a1a526600a0375b0d.

Revert "feat: use git clone filter and sparse checkout (#223)"

---

Dockerfile

Fixes the issue in bb44dbf by adding more up to date yum repos so that
we can install a version of git recent enough to support sparse
checkouts. With thanks to @christophgysin.

add up to date yum repos

---

.github/workflows/ci.yml
Dockerfile
api/async/cleanup.ts
api/async/cleanup_test.ts
api/async/publish.ts
api/async/publish_test.ts
api/async/stargazers.ts
api/async/stargazers_test.ts
api/builds/get.ts
api/builds/get_test.ts
api/modules/get.ts
api/modules/get_test.ts
api/modules/list.ts
api/modules/list_test.ts
api/stats.ts
api/stats_test.ts
api/webhook/github.ts
api/webhook/github_create_test.ts
api/webhook/github_ping_test.ts
api/webhook/github_push_test.ts
deps.ts
docker-compose.yml
run-tests.sh
test_deps.ts
utils/database.ts
utils/database_test.ts
utils/deno.ts
utils/http.ts
utils/storage.ts

This is a reland of #274
This reland includes an additional fix that lets it correctly connect to MongoDB Atlas instances. See https://github.com/denodrivers/deno_mongo/pull/326
I have tested that the driver can now correctly connect to our database and serve requests. :fingers_crossed: this is actually the final reland.

[RELAND 3] chore: update to Deno 1.17

---

utils/storage.ts

This fixes an issue where the async publish job could not run because it errors early on because no `MODERATION_BUCKET` environment variable is set.﻿

fix: ignore moderation bucket in async publish
